name: Update Request CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-request:
    runs-on: native

    steps:
      - name: Check out the repository
        uses: actions/checkout@v6

      - name: Update flake.lock
        run: |
          git config --global user.name 'forgejo-actions[bot]'
          git config --global user.email 'support@kolyma.uz'
          nix flake update --commit-lock-file

      - name: Push changes
        run: |
          git config --global user.name 'forgejo-actions[bot]'
          git config --global user.email 'support@kolyma.uz'
          git push
